### ISSUE TITLE
Comment support for NND timeshifted livestreams

### ISSUE THREAD

**Issue by Cak3lies** [animelover1984/youtube-dl#9]
## Checklist

- [x] I'm reporting a site feature request
- [x] I've verified that I'm running youtube-dl version **2020.07.28**
- [x] I've searched the bugtracker for similar site feature requests including closed ones

## Description

Comments are successfully downloaded from the normal NND site, but issuing the `--get-comments` flag on a NND livestream does not seem to have any effect. If this can be implemented I'd be extremely grateful.

Links of livestreams attempted: 
https://live2.nicovideo.jp/watch/lv327626496 (24 hours)
https://live2.nicovideo.jp/watch/lv327626435 (Japan only, VPN used)

**Comment by bbepis** [comment]
It should be straightforward to get comments saved to the info.json file, however exporting them as danmaku might be extremely difficult depending on the comment format returned by NND's livestream API.

**Comment by bbepis** [comment]
This is linked to #10.
NND does not provide a comment list independently of the stream; the comments are actually streamed to the client alongside the video data itself.
This is also subject to the same restrictions in #10 regarding download speed.

This issue is much, much more complex as a result, since youtube-dl's existing code exists all metadata like comments to be extracted before the media download begins. I'd have to rewrite some of the core logic to get this working

**Comment by bbepis** [comment]
This has been addressed in https://github.com/animelover1984/youtube-dl/commit/301a2e280b573fdf3058f649d312a6e895f863ca
